### ISSUE TITLE
某种情况下/vendor/workbunny/webman-push-server/src/HookServer.php:180会报错

### ISSUE THREAD

**Issue by x915826644** [workbunny/webman-push-server#18]
ErrorException: Array to string conversion in /Users/chen/developer/webman-chat/vendor/workbunny/webman-push-server/src/HookServer.php:180
Stack trace:
#0 [internal function]: {closure}(2, 'Array to string...', '/Users/chen/dev...', 180)
#1 /Users/chen/developer/webman-chat/vendor/workbunny/webman-push-server/src/HookServer.php(180): Redis->xack('workbunny:webma...', 'workbunny:webma...', Array)

这是报错时打印出来的数据
string(43) "workbunny:webman-push-server:webhook-stream"
string(60) "workbunny:webman-push-server:webhook-stream:event-hook-group"
array(1) {
  [1]=>
  array(1) {
    [0]=>
    string(15) "1706934636800-0"
  }
}
<img width="689" alt="image" src="https://github.com/workbunny/webman-push-server/assets/58025575/0107c574-0aed-4c63-ae6f-8dc6b3826d3e">

**Comment by chaz6chez** [comment]
请提供一下以下信息：
1. PHP版本
2. 运行环境
3. workerman/webman 驱动
4. push-server版本

**Comment by chaz6chez** [comment]
看idArray像是多级数组了，我好像没遇到过这样的情况；
1. redis版本是多少？
2. 这样的情况是偶发吗？

**Comment by chaz6chez** [comment]
已尝试修复，请使用最新版

**Comment by chen91588** [comment]
好的谢谢
