### ISSUE TITLE
win系统内存泄露,这是什么原因?

### ISSUE THREAD

**Issue by djfbob** [workbunny/webman-push-server#21]
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 398462976 bytes) in D:\kok\yuanwebman\webman\vendor\workbunny\webman-push-server\src\WebhookHandler.php on line 43
Worker process terminated with ERROR: E_ERROR "Allowed memory size of 1073741824 bytes exhausted (tried to allocate 398462976 bytes) in D:\kok\yuanwebman\webman\vendor\workbunny\webman-push-server\src\WebhookHandler.php on line 43"
process D:\kok\yuanwebman\webman\runtime\windows\start_plugin.workbunny.webman-push-server.hook-server.php terminated and try to restart
plugin.workbunny.webman-push-server.hook-server none                                1           [ok]

**Comment by chaz6chez** [comment]
windows下请使用 单进程版push-server https://www.workerman.net/plugin/2
