### ISSUE TITLE
测试的一些问题

### ISSUE THREAD

**Issue by 2723659854** [workbunny/webman-push-server#7]
1，前端无法订阅私有连接，报错：Received invalid JSON workbunny:d1b1a8016284207d7ca17c3f793c4aee24b75e78103f51108e2af2ec953f5120
2，push.Js接受的消息，没有判断到底是不是json就直接当做json解析
3，server后台，获取query参数的时候没有判断是否存在这个参数
4，api后台，无法使用报错:auth_key should be a valid app key
5，api更换委官方api,报错："error":"Invalid auth_key"，修改API.PHP的$this->_settings['base_path'] = '/apps/1‘后报错：{"error":"Invalid signature"}

**Comment by chaz6chez** [comment]
我们也测试发现了上述bug，正在完善测试用例并且修复，感谢issue！🙏
